class DocumentationEngine:

    def build_readme(
        self,
        node_count,
        link_count,
        complexity,
        health,
        categories,
        optimizations
    ):

        category_text = ""

        for key, value in categories.items():

            category_text += (
                f"- {key}: {value}\n"
            )

        optimization_text = ""

        for item in optimizations:

            optimization_text += (
                f"- {item}\n"
            )

        return f"""# Workflow Documentation

## Statistics

Nodes: {node_count}

Links: {link_count}

Complexity: {complexity}/100

Health: {health}/100

## Categories

{category_text}

## Optimization Suggestions

{optimization_text}

Generated by ComfyFlow Insight
"""